# Created by Jekyll Writer
title: Sinlion-Blog
author: Sinlion
description: Some things of me.
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: '-'
github_username: sinsinlion
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: ''
